services:
  - type: cron
    name: webbia-scraper-v2
    schedule: "@hourly"
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: API_KEY
        value: ${API_KEY}
